- name: Setup SSH Password
        run: |
          # 1. تثبيت الـ SSH سيرفر
          sudo apt update && sudo apt install -y openssh-server
          
          # 2. تغيير باسورد الـ root
          echo "root:kali123" | sudo chpasswd
          
          # 3. تعديل ملف الإعدادات للسماح بالدخول كـ root وباسورد (مهم جداً!)
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          
          # 4. ريستارت للخدمة عشان التعديلات تسمع
          sudo service ssh restart
