- name: Setup SSH Password & Fix Permissions
        run: |
          sudo apt update && sudo apt install -y openssh-server
          
          # تعيين الباسورد
          echo "root:kali123" | sudo chpasswd
          
          # مسح أي إعدادات قديمة وإضافة الإعدادات اللي بتسمح بالدخول فوراً
          sudo sed -i 's/.*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/.*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          
          # تأكيد تغيير الإعدادات في ملف منفصل لضمان العمل
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config.d/allow-root.conf
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config.d/allow-root.conf
          
          # إعادة تشغيل الخدمة
          sudo service ssh restart
